### ISSUE TITLE
not working with the new Changes on Twitch :-(

### ISSUE THREAD

**Issue by MaxxiSteel** [tranquiliza/MultiChatBanner#1]
Hi, 
Twitch disable the /ban command via IRC-Interface  today
(more Details https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486).

Is there a plan to adapt this great tool to the new api-interface?

**Comment by tranquiliza** [comment]
Hi Maxxii :) 

Sorry for the late reply, currently I do not have intentions of updating the tool :( 

Honestly did not think anyone uses the tool :D
